name: Export Railway DB to GitHub

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 UTC
  workflow_dispatch:     # Also allow manual trigger

jobs:
  export-db:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Dump the database
        run: |
          mkdir -p db
          pg_dump "$DATABASE_URL" > db/dump.sql

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add db/dump.sql
          git diff --cached --quiet || git commit -m "Auto DB export: $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
